name: CI/CD Node + Jest + Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests Jest
        run: npm test

      - name: Lancer le serveur + Cypress
        run: npx start-server-and-test start http://localhost:3000 cy:run
